spring:
  application:
    name: zk-clent
  cloud:
    zookeeper:
      connect-string: 0.0.0.0:2181
      discovery:
        register: true
        enabled: true
        instance-id: 1
        root: /app-zk-server
server:
  port: 7061
