spring:
  application:
    name: api-gateway
  cloud:
    zookeeper:
      connect-string: 0.0.0.0:2181
      discovery:
        register: true
        enabled: true
        instance-id: 4
        root: /app-zk-server
server:
  port: 8061
zuul:
  routes:
    mprovider:
      path: /**
      serviceId: micro-provider
